#!/usr/bin/env python3
"""Generate pretext_fold.h - the stepping table for preText()'s fallback chain.

WHY THIS IS GENERATED
---------------------
preText() must degrade gracefully against ANY display font: a font that has the
glyph keeps it, a font that has a *nearer* representation gets that instead, and
only when nothing is available does the codepoint become a substitute.  That
needs a one-step mapping table walked as a chain, and the contents are Unicode
facts, so the table is generated (the fonts are generated by bdf2adafruit3.py in
the same spirit).  This file is the audit trail.

THE ONE RULE
------------
For each codepoint outside ASCII, the first of these that applies wins:

  1. OVERRIDES          - the hand-picked visual or transliteration choice, and
                          every place a decomposition would be wrong or would
                          lead somewhere silly.
  2. canonical base     - NFD, combining marks stripped.  Keeps the SAME script
                          where possible, so a font with Greek gets Greek:
                          U+1F00 -> U+03B1 (alpha), U+0450 -> U+0435 (ie).
  3. NFKD first ASCII   - the first ASCII character of the compatibility
                          decomposition.  This is what covers the "letter and
                          digit" forms without a hand-written table: fullwidth
                          (U+FF21 -> A), mathematical alphanumerics
                          (U+1D400 -> A), enclosed alphanumerics (U+2460 -> 1),
                          Roman numerals (U+216B -> X), number forms
                          (U+00BD -> 1), superscripts, presentation forms
                          (U+FB03 -> f), letterlike symbols (U+2116 -> N).
  4. name lookalike     - Greek and Cyrillic base letters have no decomposition
                          at all, so their ASCII stand-in comes from the letter
                          name: CYRILLIC SMALL LETTER DE -> d.

Note what the rule deliberately does NOT do: decorative symbols have no
decomposition, so U+263A and U+2713 fall through to the substitute instead of
being "translated" into punctuation.  That is the agreed policy, and it is
enforced by Unicode data rather than by a hand-maintained deny list.

Because steps 2/3/4 can land on a non-ASCII codepoint that is itself a key in
this table, preText() walks the table as a chain and re-tests the font after
every step.  That is what lets one table serve both a font with Greek and a font
without it: U+1F00 -> alpha (accepted by a Greek font) -> a (accepted by a Latin
font).

Run:  python src/displays/tools/gen_fold_table.py          (regenerate)
      python src/displays/tools/gen_fold_table.py --stats  (coverage report)
The generated header is committed; this script is a maintenance tool and is not
part of the build.
"""

import pathlib
import sys
import unicodedata

OUT_PATH = pathlib.Path(__file__).with_name("pretext_fold.h")

# Ranges that never receive a mapping: ASCII needs none, controls are consumed by
# the renderer before preText() sees them, and the rest are not text.
SKIP_RANGES = [
    (0x0000, 0x007F),  # ASCII and C0 controls
    (0x0080, 0x009F),  # C1 controls
    (0xD800, 0xDFFF),  # surrogates
    (0xE000, 0xF8FF),  # private use
    (0xF0000, 0x10FFFF),  # planes 15-16 (private use)
]

# The renderer's UTF-8 decoder handles four-byte sequences, so supplementary
# planes do reach preText().  They are scanned only where a decomposition can
# actually produce something - which is where the mathematical alphanumerics
# live.  Extend this list rather than scanning whole planes: emoji and CJK
# cannot decompose, so they would cost generation time and flash for nothing.
SUPPLEMENTARY_RANGES = [
    (0xAB30, 0xAB6F),    # Latin Extended-E
    (0x1D400, 0x1D7FF),  # Mathematical Alphanumeric Symbols
    (0x1F100, 0x1F1FF),  # Enclosed Alphanumeric Supplement
    (0x1FBF0, 0x1FBF9),  # Segmented Digits
]

# Hand-picked choices.  This layer exists for three reasons: letters the
# transliteration convention spells differently from their name, symbols whose
# decomposition is a word rather than a symbol, and codepoints with no
# decomposition at all that still have an obvious ASCII stand-in.
OVERRIDES = {
    # -- Latin-1 Supplement: ligatures, strokes, caseless letters, ordinals
    0x00A0: 0x0020,  # no-break space
    0x00AA: 0x0061,  # feminine ordinal             -> a
    0x00B0: 0x006F,  # degree sign "deg" would give d, an o reads better
    0x00B5: 0x0075,  # micro sign (decomposes to Greek mu, needs u)
    0x00BA: 0x006F,  # masculine ordinal            -> o
    0x00C6: 0x0041, 0x00E6: 0x0061,  # AE / ae
    0x00D0: 0x0044, 0x00F0: 0x0064,  # Eth
    0x00D8: 0x004F, 0x00F8: 0x006F,  # O with stroke
    0x00DE: 0x0050, 0x00FE: 0x0070,  # Thorn
    0x00DF: 0x0073,                  # sharp s (decomposes to "ss", one char)
    # -- Latin Extended-A: strokes and caseless letters
    0x0110: 0x0044, 0x0111: 0x0064,
    0x0126: 0x0048, 0x0127: 0x0068,
    0x0130: 0x0049, 0x0131: 0x0069,  # dotted / dotless I
    0x0132: 0x0049, 0x0133: 0x0069,  # IJ ligature
    0x0138: 0x006B,                  # kra, no uppercase form
    0x013F: 0x004C, 0x0140: 0x006C,
    0x0141: 0x004C, 0x0142: 0x006C,
    0x0149: 0x006E,
    0x014A: 0x004E, 0x014B: 0x006E,  # Eng
    0x0152: 0x004F, 0x0153: 0x006F,  # OE ligature
    0x0166: 0x0054, 0x0167: 0x0074,
    0x017F: 0x0073,                  # long s
    # -- Latin Extended-B: the non-decomposable remainder
    0x0180: 0x0062, 0x0181: 0x0042, 0x0182: 0x0042, 0x0183: 0x0062,
    0x0184: 0x0036, 0x0185: 0x0036,  # tone six -> 6
    0x0186: 0x004F, 0x0187: 0x0043, 0x0188: 0x0063,
    0x0189: 0x0044, 0x018A: 0x0044, 0x018B: 0x0044, 0x018C: 0x0064, 0x018D: 0x0064,
    0x018E: 0x0045, 0x018F: 0x0045, 0x0190: 0x0045,
    0x0191: 0x0046, 0x0192: 0x0066,
    0x0193: 0x0047, 0x0194: 0x0047, 0x0195: 0x0068,
    0x0196: 0x0049, 0x0197: 0x0049, 0x0198: 0x004B, 0x0199: 0x006B,
    0x019A: 0x006C, 0x019B: 0x006C, 0x019C: 0x004D, 0x019D: 0x004E, 0x019E: 0x006E,
    0x019F: 0x004F, 0x01A0: 0x004F, 0x01A1: 0x006F, 0x01A2: 0x004F, 0x01A3: 0x006F,
    0x01A4: 0x0050, 0x01A5: 0x0070, 0x01A6: 0x0052, 0x01A7: 0x0053, 0x01A8: 0x0073,
    0x01A9: 0x0053, 0x01AA: 0x0073, 0x01AB: 0x0074,
    0x01AC: 0x0054, 0x01AD: 0x0074, 0x01AE: 0x0054, 0x01AF: 0x0055, 0x01B0: 0x0075,
    0x01B1: 0x0055, 0x01B2: 0x0056, 0x01B3: 0x0059, 0x01B4: 0x0079,
    0x01B5: 0x005A, 0x01B6: 0x007A, 0x01B7: 0x005A, 0x01B8: 0x005A,
    0x01B9: 0x007A, 0x01BA: 0x007A, 0x01BB: 0x007A,
    0x01BC: 0x0035, 0x01BD: 0x0035,  # tone five -> 5
    0x01BE: 0x0074, 0x01BF: 0x0077,  # glottal stop with stroke, wynn
    0x01C0: 0x007C, 0x01C1: 0x007C, 0x01C2: 0x007C, 0x01C3: 0x0021,  # clicks
    0x01C4: 0x0044, 0x01C5: 0x0044, 0x01C6: 0x0064,  # DZ
    0x01C7: 0x004C, 0x01C8: 0x004C, 0x01C9: 0x006C,  # LJ
    0x01CA: 0x004E, 0x01CB: 0x004E, 0x01CC: 0x006E,  # NJ
    0x01DD: 0x0065, 0x01EE: 0x005A, 0x01EF: 0x007A, 0x01F0: 0x006A,
    0x01F1: 0x0044, 0x01F2: 0x0044, 0x01F3: 0x0064,
    0x01F6: 0x0048, 0x01F7: 0x0057,
    0x021C: 0x005A, 0x021D: 0x007A,  # yogh
    0x0220: 0x004E, 0x0221: 0x0064, 0x0222: 0x004F, 0x0223: 0x006F,
    0x0224: 0x005A, 0x0225: 0x007A,
    0x0234: 0x006C, 0x0235: 0x006E, 0x0236: 0x0074, 0x0237: 0x006A,
    0x0238: 0x0062, 0x0239: 0x0070,
    0x023A: 0x0041, 0x023B: 0x0043, 0x023C: 0x0063, 0x023D: 0x004C, 0x023E: 0x0054,
    0x023F: 0x0073, 0x0240: 0x007A, 0x0241: 0x003F, 0x0242: 0x003F,
    0x0243: 0x0042, 0x0244: 0x0055, 0x0245: 0x0056, 0x0246: 0x0045, 0x0247: 0x0065,
    0x0248: 0x004A, 0x0249: 0x006A, 0x024A: 0x0051, 0x024B: 0x0071,
    0x024C: 0x0052, 0x024D: 0x0072, 0x024E: 0x0059, 0x024F: 0x0079,
    # -- IPA Extensions: no decompositions at all, so all of it is here
    0x0250: 0x0061, 0x0251: 0x0061, 0x0252: 0x0061, 0x0253: 0x0062, 0x0254: 0x006F,
    0x0255: 0x0063, 0x0256: 0x0064, 0x0257: 0x0064, 0x0258: 0x0065, 0x0259: 0x0065,
    0x025A: 0x0065, 0x025B: 0x0065, 0x025C: 0x0065, 0x025D: 0x0065, 0x025E: 0x0065,
    0x025F: 0x006A, 0x0260: 0x0067, 0x0261: 0x0067, 0x0262: 0x0047, 0x0263: 0x0067,
    0x0264: 0x0067, 0x0265: 0x0068, 0x0266: 0x0068, 0x0267: 0x0068, 0x0268: 0x0069,
    0x0269: 0x0069, 0x026A: 0x0049, 0x026B: 0x006C, 0x026C: 0x006C, 0x026D: 0x006C,
    0x026E: 0x006C, 0x026F: 0x006D, 0x0270: 0x006D, 0x0271: 0x006D, 0x0272: 0x006E,
    0x0273: 0x006E, 0x0274: 0x004E, 0x0275: 0x006F, 0x0276: 0x006F, 0x0277: 0x006F,
    0x0278: 0x0066, 0x0279: 0x0072, 0x027A: 0x0072, 0x027B: 0x0072, 0x027C: 0x0072,
    0x027D: 0x0072, 0x027E: 0x0072, 0x027F: 0x0072, 0x0280: 0x0052, 0x0281: 0x0052,
    0x0282: 0x0073, 0x0283: 0x0073, 0x0284: 0x006A, 0x0285: 0x0073, 0x0286: 0x0073,
    0x0287: 0x0074, 0x0288: 0x0074, 0x0289: 0x0075, 0x028A: 0x0075, 0x028B: 0x0076,
    0x028C: 0x0076, 0x028D: 0x0077, 0x028E: 0x0079, 0x028F: 0x0059, 0x0290: 0x007A,
    0x0291: 0x007A, 0x0292: 0x007A, 0x0293: 0x007A, 0x0294: 0x003F, 0x0295: 0x003F,
    0x0296: 0x003F, 0x0297: 0x0063, 0x0298: 0x006F, 0x0299: 0x0042, 0x029A: 0x0065,
    0x029B: 0x0067, 0x029C: 0x0048, 0x029D: 0x006A, 0x029E: 0x006B, 0x029F: 0x004C,
    0x02A0: 0x0071, 0x02A1: 0x003F, 0x02A2: 0x003F, 0x02A3: 0x0064, 0x02A4: 0x0064,
    0x02A5: 0x0064, 0x02A6: 0x0074, 0x02A7: 0x0074, 0x02A8: 0x0074,
    # -- Spacing Modifier Letters: accents and superscripts
    0x02B0: 0x0068, 0x02B1: 0x0068, 0x02B2: 0x006A, 0x02B3: 0x0072, 0x02B4: 0x0072,
    0x02B5: 0x0072, 0x02B6: 0x0052, 0x02B7: 0x0077, 0x02B8: 0x0079,
    0x02B9: 0x0027, 0x02BA: 0x0022, 0x02BB: 0x0027, 0x02BC: 0x0027, 0x02BD: 0x0027,
    0x02BE: 0x0027, 0x02BF: 0x0027, 0x02C0: 0x003F, 0x02C1: 0x003F,
    0x02C2: 0x003C, 0x02C3: 0x003E, 0x02C4: 0x005E, 0x02C5: 0x0076,
    0x02C6: 0x005E, 0x02C7: 0x005E, 0x02C8: 0x0027, 0x02C9: 0x002D, 0x02CA: 0x0027,
    0x02CB: 0x0027, 0x02CC: 0x002C, 0x02CD: 0x002D, 0x02CE: 0x0027, 0x02CF: 0x0027,
    0x02D0: 0x003A, 0x02D1: 0x003A, 0x02D8: 0x005E, 0x02D9: 0x002E, 0x02DA: 0x006F,
    0x02DB: 0x002C, 0x02DC: 0x007E, 0x02DD: 0x0022, 0x02DF: 0x0078,
    0x02E0: 0x0067, 0x02E1: 0x006C, 0x02E2: 0x0073, 0x02E3: 0x0078, 0x02E4: 0x003F,
    # -- Cyrillic: fold to the base Cyrillic letter first, so a Cyrillic font
    #    keeps Cyrillic and only a Latin-only font falls through to the
    #    lookalike on the next chain step.
    0x0400: 0x0415, 0x0450: 0x0435, 0x0402: 0x0414, 0x0452: 0x0434,
    0x0403: 0x0413, 0x0453: 0x0433, 0x0405: 0x0421, 0x0455: 0x0441,
    0x0408: 0x0419, 0x0458: 0x0439, 0x0409: 0x041B, 0x0459: 0x043B,
    0x040A: 0x041D, 0x045A: 0x043D, 0x040B: 0x0422, 0x045B: 0x0442,
    0x040C: 0x041A, 0x045C: 0x043A, 0x040D: 0x0418, 0x045D: 0x0438,
    0x040F: 0x0426, 0x045F: 0x0446,
    0x0490: 0x0413, 0x0491: 0x0433, 0x0492: 0x0413, 0x0493: 0x0433,
    0x0494: 0x0413, 0x0495: 0x0433, 0x0496: 0x0416, 0x0497: 0x0436,
    0x0498: 0x0417, 0x0499: 0x0437, 0x049A: 0x041A, 0x049B: 0x043A,
    0x049C: 0x041A, 0x049D: 0x043A, 0x049E: 0x041A, 0x049F: 0x043A,
    0x04A0: 0x041A, 0x04A1: 0x043A, 0x04A2: 0x041D, 0x04A3: 0x043D,
    0x04A4: 0x041D, 0x04A5: 0x043D, 0x04A6: 0x041F, 0x04A7: 0x043F,
    0x04A8: 0x0425, 0x04A9: 0x0445, 0x04AA: 0x0421, 0x04AB: 0x0441,
    0x04AC: 0x0422, 0x04AD: 0x0442, 0x04AE: 0x0423, 0x04AF: 0x0443,
    0x04B0: 0x0423, 0x04B1: 0x0443, 0x04B2: 0x0425, 0x04B3: 0x0445,
    0x04B4: 0x0426, 0x04B5: 0x0446, 0x04B6: 0x0427, 0x04B7: 0x0447,
    0x04B8: 0x0427, 0x04B9: 0x0447, 0x04BA: 0x0425, 0x04BB: 0x0445,
    0x04BC: 0x0427, 0x04BD: 0x0447, 0x04BE: 0x0427, 0x04BF: 0x0447,
    0x04C0: 0x0406, 0x04C1: 0x0416, 0x04C2: 0x0436, 0x04C3: 0x041A,
    0x04C4: 0x043A, 0x04C5: 0x041B, 0x04C6: 0x043B, 0x04C7: 0x041D,
    0x04C8: 0x043D, 0x04C9: 0x041D, 0x04CA: 0x043D, 0x04CB: 0x0427,
    0x04CC: 0x0447, 0x04CD: 0x041C, 0x04CE: 0x043C, 0x04D0: 0x0410,
    0x04D1: 0x0430, 0x04D2: 0x0410, 0x04D3: 0x0430, 0x04D4: 0x0410,
    0x04D5: 0x0430, 0x04D6: 0x0415, 0x04D7: 0x0435, 0x04D8: 0x0410,
    0x04D9: 0x0430, 0x04DA: 0x0410, 0x04DB: 0x0430, 0x04DC: 0x0416,
    0x04DD: 0x0436, 0x04DE: 0x0417, 0x04DF: 0x0437, 0x04E0: 0x0417,
    0x04E1: 0x0437, 0x04E2: 0x0418, 0x04E3: 0x0438, 0x04E4: 0x0418,
    0x04E5: 0x0438, 0x04E6: 0x041E, 0x04E7: 0x043E, 0x04E8: 0x041E,
    0x04E9: 0x043E, 0x04EA: 0x041E, 0x04EB: 0x043E, 0x04EC: 0x042D,
    0x04ED: 0x044D, 0x04EE: 0x0423, 0x04EF: 0x0443, 0x04F0: 0x0423,
    0x04F1: 0x0443, 0x04F2: 0x0423, 0x04F3: 0x0443, 0x04F4: 0x0427,
    0x04F5: 0x0447, 0x04F6: 0x0413, 0x04F7: 0x0433, 0x04F8: 0x042B,
    0x04F9: 0x044B,
    # -- Cyrillic Supplement: none have decompositions, so all are lookalikes
    0x0500: 0x041A, 0x0501: 0x043A, 0x0502: 0x0428, 0x0503: 0x0448,
    0x0504: 0x0417, 0x0505: 0x0437, 0x0506: 0x0426, 0x0507: 0x0446,
    0x0508: 0x0427, 0x0509: 0x0447, 0x050A: 0x0428, 0x050B: 0x0448,
    0x050C: 0x0417, 0x050D: 0x0437, 0x050E: 0x042A, 0x050F: 0x044A,
    0x0510: 0x0423, 0x0511: 0x0443, 0x0512: 0x041A, 0x0513: 0x043A,
    0x0514: 0x041E, 0x0515: 0x043E, 0x0516: 0x0423, 0x0517: 0x0443,
    0x0518: 0x0417, 0x0519: 0x0437, 0x051A: 0x0414, 0x051B: 0x0434,
    0x051C: 0x0428, 0x051D: 0x0448,
    0x0524: 0x041F, 0x0525: 0x043F, 0x0526: 0x0422, 0x0527: 0x0442,
    0x0528: 0x041B, 0x0529: 0x043B, 0x052A: 0x0414, 0x052B: 0x0434,
    0x052C: 0x0414, 0x052D: 0x0434, 0x052E: 0x041B, 0x052F: 0x043B,
    # -- Latin Extended-C
    0x2C60: 0x004C, 0x2C61: 0x006C, 0x2C62: 0x004C, 0x2C63: 0x0050, 0x2C64: 0x0052,
    0x2C65: 0x0061, 0x2C66: 0x0074, 0x2C67: 0x0048, 0x2C68: 0x0068, 0x2C69: 0x004B,
    0x2C6A: 0x006B, 0x2C6B: 0x005A, 0x2C6C: 0x007A, 0x2C6D: 0x0041, 0x2C6E: 0x004D,
    0x2C6F: 0x0041, 0x2C70: 0x0041, 0x2C71: 0x0076, 0x2C72: 0x0057, 0x2C73: 0x0077,
    0x2C74: 0x0076, 0x2C75: 0x0048, 0x2C76: 0x0068, 0x2C77: 0x0074, 0x2C78: 0x0065,
    0x2C79: 0x0072, 0x2C7A: 0x006F, 0x2C7B: 0x0065, 0x2C7C: 0x006A, 0x2C7D: 0x0056,
    0x2C7E: 0x0053, 0x2C7F: 0x007A,
    # -- Latin Extended-D: the letter-like ones; runic and old-italic are left out
    0xA726: 0x0048, 0xA727: 0x0068, 0xA728: 0x005A, 0xA729: 0x007A,
    0xA730: 0x0066, 0xA731: 0x0073, 0xA732: 0x0041, 0xA733: 0x0061,
    0xA734: 0x004F, 0xA735: 0x006F, 0xA736: 0x0055, 0xA737: 0x0075,
    0xA738: 0x0041, 0xA739: 0x0061, 0xA73A: 0x004F, 0xA73B: 0x006F,
    0xA73C: 0x004F, 0xA73D: 0x006F, 0xA73E: 0x0043, 0xA73F: 0x0063,
    0xA740: 0x004B, 0xA741: 0x006B, 0xA742: 0x004B, 0xA743: 0x006B,
    0xA744: 0x004B, 0xA745: 0x006B, 0xA746: 0x004C, 0xA747: 0x006C,
    0xA748: 0x004C, 0xA749: 0x006C, 0xA74A: 0x004F, 0xA74B: 0x006F,
    0xA74C: 0x004F, 0xA74D: 0x006F, 0xA74E: 0x004F, 0xA74F: 0x006F,
    0xA750: 0x0050, 0xA751: 0x0070, 0xA752: 0x0050, 0xA753: 0x0070,
    0xA754: 0x0050, 0xA755: 0x0070, 0xA756: 0x0051, 0xA757: 0x0071,
    0xA758: 0x0051, 0xA759: 0x0071, 0xA75A: 0x0052, 0xA75B: 0x0072,
    0xA75C: 0x0052, 0xA75D: 0x0072, 0xA75E: 0x0056, 0xA75F: 0x0076,
    0xA760: 0x0059, 0xA761: 0x0079, 0xA762: 0x005A, 0xA763: 0x007A,
    0xA764: 0x0054, 0xA765: 0x0074, 0xA766: 0x0054, 0xA767: 0x0074,
    0xA768: 0x0056, 0xA769: 0x0076, 0xA76A: 0x0045, 0xA76B: 0x0065,
    0xA76C: 0x0058, 0xA76D: 0x0078, 0xA76E: 0x0043, 0xA76F: 0x0063,
    0xA779: 0x0044, 0xA77A: 0x0064, 0xA77B: 0x0046, 0xA77C: 0x0066,
    0xA77D: 0x0047, 0xA77E: 0x0047, 0xA77F: 0x0067, 0xA780: 0x004C,
    0xA781: 0x006C, 0xA782: 0x0052, 0xA783: 0x0072, 0xA784: 0x0053,
    0xA785: 0x0073, 0xA786: 0x0054, 0xA787: 0x0074, 0xA789: 0x003A,
    0xA78A: 0x003D, 0xA78B: 0x0053, 0xA78C: 0x0027, 0xA78D: 0x0048,
    0xA78E: 0x006C, 0xA78F: 0x003F, 0xA790: 0x004E, 0xA791: 0x006E,
    0xA792: 0x0043, 0xA793: 0x0063, 0xA794: 0x0063, 0xA795: 0x0068,
    0xA796: 0x0042, 0xA797: 0x0062, 0xA798: 0x0046, 0xA799: 0x0066,
    0xA7A0: 0x0047, 0xA7A1: 0x0067, 0xA7A2: 0x004B, 0xA7A3: 0x006B,
    0xA7A4: 0x004E, 0xA7A5: 0x006E, 0xA7A6: 0x0052, 0xA7A7: 0x0072,
    0xA7A8: 0x0053, 0xA7A9: 0x0073, 0xA7AA: 0x0048, 0xA7AB: 0x0045,
    0xA7AC: 0x0047, 0xA7AD: 0x004C, 0xA7AE: 0x0049, 0xA7B0: 0x004B,
    0xA7B1: 0x0054, 0xA7B2: 0x004A, 0xA7B3: 0x0058, 0xA7B4: 0x0042,
    0xA7B5: 0x0062, 0xA7B6: 0x004F, 0xA7B7: 0x006F, 0xA7B8: 0x0055,
    0xA7B9: 0x0075,
    # -- Symbols and punctuation.  Most of these have NO decomposition at all, so
    #    the NFKD rule cannot reach them and the choice has to be made here.
    #    Decorative symbols are deliberately absent: they resolve to the
    #    substitute, which is the agreed policy.
    0x2000: 0x0020, 0x2001: 0x0020, 0x2002: 0x0020, 0x2003: 0x0020,
    0x2004: 0x0020, 0x2005: 0x0020, 0x2006: 0x0020, 0x2007: 0x0020,
    0x2008: 0x0020, 0x2009: 0x0020, 0x200A: 0x0020,  # en quad .. hair space
    0x200B: 0x0020, 0x200C: 0x0020,                  # zero width space, ZWNJ
    0x2010: 0x002D, 0x2011: 0x002D, 0x2012: 0x002D,  # hyphen, non-breaking
    0x2013: 0x002D, 0x2014: 0x002D, 0x2015: 0x002D,  # en/em dash, horizontal bar
    0x2018: 0x0027, 0x2019: 0x0027, 0x201A: 0x002C, 0x201B: 0x0027,
    0x201C: 0x0022, 0x201D: 0x0022, 0x201E: 0x0022, 0x201F: 0x0022,
    0x2020: 0x002B, 0x2021: 0x002B,                  # dagger
    0x2022: 0x002E,                                  # bullet, outside font range
    0x2026: 0x002E,                                  # ellipsis
    0x202F: 0x0020, 0x205F: 0x0020, 0x3000: 0x0020,  # narrow/medium/ideographic space
    0x2030: 0x0025,                                  # per mille; "0/00" would give 0
    0x2032: 0x0027, 0x2033: 0x0022,                  # prime, double prime
    0x2039: 0x003C, 0x203A: 0x003E,                  # single guillemets
    0x203C: 0x0021, 0x2044: 0x002F,                  # double bang, fraction slash
    0x2045: 0x005B, 0x2046: 0x005D,
    0x2052: 0x0025,                                  # commercial minus
    0x20AC: 0x0045,                                  # euro -> E
    0x2116: 0x004E,                                  # numero -> N
    0x2117: 0x0050, 0x2120: 0x0053,                  # sound recording, service mark
}

# Letter names (Unicode name minus the script/case prefix, spaces removed) that
# must not use their own first letter.  Everything else falls back to the first
# letter of the name, so only the exceptions need listing.
LETTER_OVERRIDES = {
    "FINALSIGMA": "s", "PHI": "f", "SHORTI": "i", "HARDSIGN": "'",
    "SOFTSIGN": "'", "YERU": "y", "EF": "f", "TSE": "c", "SHA": "s",
    "SHCHA": "s", "YAT": "e", "DZHE": "d", "LJE": "l", "NJE": "n",
    "TSHE": "t", "DJE": "d", "GJE": "g", "KJE": "k", "DZE": "s",
    "ZHE": "z", "EM": "m", "EN": "n", "ER": "r", "ES": "s", "EL": "l",
    "KA": "k", "PE": "p", "TE": "t", "GE": "g", "DE": "d", "VE": "v",
    "BE": "b", "YA": "y", "YU": "y", "YO": "y", "KOPPA": "k", "STIGMA": "s",
    "DIGAMMA": "d", "SAMP I": "s", "SHO": "s", "OMEGA": "o", "OMICRON": "o",
    "PSI": "p", "XI": "x", "ETA": "e", "THETA": "t", "UPSILON": "u",
    "IOTA": "i", "KAPPA": "k", "LAMDA": "l", "LAMBDA": "l", "MU": "m",
    "NU": "n", "PI": "p", "RHO": "r", "SIGMA": "s", "TAU": "t", "ZETA": "z",
    "GAMMA": "g", "DELTA": "d", "EPSILON": "e", "BETA": "b", "ALPHA": "a",
}

BMP = (0x0080, 0xFFFF)


def canonical_base(ch):
    """Base codepoint after stripping combining marks, or None."""
    decomposed = unicodedata.normalize("NFD", ch)
    base = "".join(c for c in decomposed if unicodedata.category(c) != "Mn")
    if len(base) == 1 and base != ch:
        return ord(base)
    return None


def nfkd_stripped(ch):
    """Compatibility decomposition with combining marks removed."""
    return [c for c in unicodedata.normalize("NFKD", ch)
            if unicodedata.category(c) != "Mn"]


def name_lookalike(ch):
    """ASCII stand-in for a Greek or Cyrillic letter, from its Unicode name."""
    name = unicodedata.name(ch, "")
    if not name.startswith(("GREEK ", "CYRILLIC ")):
        return None
    upper = " CAPITAL LETTER " in name
    marker = " CAPITAL LETTER " if upper else " SMALL LETTER "
    if marker not in name:
        return None
    letter = name.split(marker, 1)[1]
    letter = letter.split(" WITH ", 1)[0].strip()
    ascii_ch = LETTER_OVERRIDES.get(letter)
    if ascii_ch is None:
        ascii_ch = letter[0]
    return ord(ascii_ch.upper() if upper else ascii_ch.lower())


def candidates(cp):
    """Steps for cp in order of preference.  ASCII first, because that ends the
    chain; a non-ASCII base may follow, but see build(): it is only used when the
    base itself resolves, which is what stops Hangul (whose Jamo bases lead
    nowhere) from costing 44 KB of flash for no benefit."""
    ch = chr(cp)
    out = []

    def add(value):
        if value is not None and value != cp and value not in out:
            out.append(value)

    add(OVERRIDES.get(cp))
    add(name_lookalike(ch))
    stripped = nfkd_stripped(ch)
    for c in stripped:
        if ord(c) < 0x80:
            add(ord(c))
            break
    add(canonical_base(ch))
    if stripped:
        add(ord(stripped[0]))
    return out


def skipped(cp):
    return any(lo <= cp <= hi for lo, hi in SKIP_RANGES)


def utf8_len(cp):
    if cp < 0x80:
        return 1
    if cp < 0x800:
        return 2
    if cp < 0x10000:
        return 3
    return 4


def assert_byte_monotonic(entries):
    """Every step must fit in the bytes its codepoint came from.

    preTextString() rewrites a widget's string in place, which is only safe if
    no step grows: a two-byte codepoint may not step to a three-byte one, and no
    step may reach outside the BMP (the encoder writes three bytes at most).
    """
    bad = [(cp, nxt) for cp, nxt in entries.items()
           if utf8_len(nxt) > utf8_len(cp) or nxt > 0xFFFF]
    if bad:
        raise SystemExit(
            "steps that would grow the string (breaks in-place rewriting): %s%s"
            % (", ".join("U+%04X->U+%04X" % pair for pair in bad[:8]),
               " ..." if len(bad) > 8 else ""))

    # The table is emitted in two halves so both keep 4-byte entries: BMP keys
    # are the codepoint, plane-1 keys are the offset from 0x10000 (which fits a
    # uint16).  Anything above plane 1 would need a wider key - fail loudly
    # rather than truncate silently.
    high = [cp for cp in entries if cp > 0x1FFFF]
    if high:
        raise SystemExit("astral keys above plane 1 not supported: %s"
                         % ", ".join("U+%05X" % cp for cp in high[:8]))


def scan_codepoints():
    for lo, hi in [BMP] + SUPPLEMENTARY_RANGES:
        for cp in range(lo, hi + 1):
            if not skipped(cp):
                yield cp


def build():
    """Two phases: ASCII steps first, then non-ASCII bases that can progress.

    A non-ASCII base is only accepted once it is itself a key in the table or is
    ASCII, because otherwise the step is a dead end.  Without that guard the
    11,172 Hangul syllables each claim a Jamo base that leads nowhere - 44 KB of
    flash for no benefit - while the mathematical Greek letters keep their step
    to plain Greek, which does resolve.
    """
    cand = {}
    for cp in scan_codepoints():
        steps = candidates(cp)
        if steps:
            cand[cp] = steps

    entries = {}
    for cp, steps in cand.items():
        for value in steps:
            if value < 0x80:
                entries[cp] = value
                break

    for _ in range(4):  # chains are at most a few steps long
        added = 0
        for cp, steps in cand.items():
            if cp in entries:
                continue
            for value in steps:
                if value in entries:
                    entries[cp] = value
                    added += 1
                    break
        if not added:
            break

    assert_byte_monotonic(entries)
    return entries


def emit(entries):
    keys = sorted(entries)
    assert len(keys) == len(set(keys)), "duplicate codepoints in table"

    lines = []
    lines.append("// Generated by gen_fold_table.py - do not edit by hand.")
    lines.append("//")
    lines.append("// One step of the preText() fallback chain: walk this table, re-testing")
    lines.append("// the font after each step, and stop at the first codepoint the font can")
    lines.append("// draw.  Entries MUST stay in ascending codepoint order - the lookup is a")
    lines.append("// binary search and an out-of-order entry would silently miss.  The")
    lines.append("// generator emits sorted output and asserts uniqueness, so re-run it rather")
    lines.append("// than editing a codepoint here by hand.")
    lines.append("//")
    lines.append("// %d entries in two halves (%d bytes; GFXglyph is 8 bytes, for scale)."
                 % (len(keys), len(keys) * 4))
    lines.append("")
    lines.append("#ifndef pretext_fold_h")
    lines.append("#define pretext_fold_h")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <Arduino.h>   // PROGMEM, pgm_read_word")
    lines.append("")
    lines.append("// Two halves, each with 4-byte entries.  The low half keys on the codepoint")
    lines.append("// itself; the high half keys on the offset from 0x10000, which fits a uint16")
    lines.append("// and keeps the entries narrow.  pretext.cpp picks by range.")
    lines.append("struct PreTextFoldStep {")
    lines.append("  uint16_t key;   // codepoint, or offset from 0x10000 in the high half")
    lines.append("  uint16_t next;  // the step to try before giving up on it")
    lines.append("};")
    lines.append("")

    def emit_half(name, rows, show_blocks):
        lines.append("const PreTextFoldStep %s[] PROGMEM = {" % name)
        row = []
        current_block = None
        for key, value, block in rows:
            if show_blocks and block != current_block:
                if row:
                    lines.append("  " + " ".join(row))
                    row = []
                lines.append("  /* %s */" % block)
                current_block = block
            row.append("{0x%04X, 0x%04X},/* %s */" % (key, value, comment_for(value)))
            if len(row) == 4:
                lines.append("  " + " ".join(row))
                row = []
        if row:
            lines.append("  " + " ".join(row))
        lines.append("};")
        lines.append("")

    low = [(cp, entries[cp], block_name(cp)) for cp in keys if cp <= 0xFFFF]
    high = [(cp - 0x10000, entries[cp], block_name(cp)) for cp in keys if cp > 0xFFFF]

    emit_half("preTextFoldTable", low, True)
    emit_half("preTextFoldTableHigh", high, False)

    lines.append("#define PRETEXT_FOLD_TABLE_LEN (sizeof(preTextFoldTable) / sizeof(preTextFoldTable[0]))")
    lines.append("#define PRETEXT_FOLD_TABLE_HIGH_LEN (sizeof(preTextFoldTableHigh) / sizeof(preTextFoldTableHigh[0]))")
    lines.append("#define PRETEXT_FOLD_HIGH_BASE 0x10000UL")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def comment_for(base):
    named = {
        0x20: "space", 0x21: "!", 0x22: '"', 0x25: "%", 0x27: "'", 0x2B: "+",
        0x2C: ",", 0x2D: "-", 0x2E: ".", 0x2F: "/", 0x3A: ":", 0x3C: "<",
        0x3D: "=", 0x3E: ">", 0x3F: "?", 0x5B: "[", 0x5D: "]", 0x5E: "^",
        0x7C: "|", 0x7E: "~",
    }
    if base in named:
        return named[base]
    if 0x20 <= base < 0x7F:
        return chr(base)
    return "U+%04X" % base


# Blocks quoted in the --stats report; broader than what is mapped, so gaps show.
COVERAGE_BLOCKS = [
    (0x0080, 0x00FF, "Latin-1 Supplement"),
    (0x0100, 0x017F, "Latin Extended-A"),
    (0x0180, 0x024F, "Latin Extended-B"),
    (0x0250, 0x02AF, "IPA Extensions"),
    (0x02B0, 0x02FF, "Spacing Modifier Letters"),
    (0x0300, 0x036F, "Combining Diacritical Marks"),
    (0x0370, 0x03FF, "Greek and Coptic"),
    (0x0400, 0x04FF, "Cyrillic"),
    (0x0500, 0x052F, "Cyrillic Supplement"),
    (0x1D00, 0x1D7F, "Phonetic Extensions"),
    (0x1E00, 0x1EFF, "Latin Extended Additional"),
    (0x1F00, 0x1FFF, "Greek Extended"),
    (0x2000, 0x206F, "General Punctuation"),
    (0x2070, 0x209F, "Super and Subscripts"),
    (0x20A0, 0x20CF, "Currency Symbols"),
    (0x2100, 0x214F, "Letterlike Symbols"),
    (0x2150, 0x218F, "Number Forms"),
    (0x2190, 0x21FF, "Arrows"),
    (0x2200, 0x22FF, "Mathematical Operators"),
    (0x2460, 0x24FF, "Enclosed Alphanumerics"),
    (0x2500, 0x257F, "Box Drawing"),
    (0x25A0, 0x25FF, "Geometric Shapes"),
    (0x2600, 0x26FF, "Miscellaneous Symbols"),
    (0x2700, 0x27BF, "Dingbats"),
    (0x2C60, 0x2C7F, "Latin Extended-C"),
    (0x3000, 0x303F, "CJK Symbols and Punctuation"),
    (0x3040, 0x30FF, "Kana"),
    (0x3300, 0x33FF, "CJK Compatibility"),
    (0x4E00, 0x9FFF, "CJK Unified Ideographs"),
    (0xA640, 0xA69F, "Cyrillic Extended-B"),
    (0xA720, 0xA7FF, "Latin Extended-D"),
    (0xAC00, 0xD7AF, "Hangul Syllables"),
    (0xFB00, 0xFB4F, "Alphabetic Presentation Forms"),
    (0xFF00, 0xFFEF, "Halfwidth and Fullwidth Forms"),
    (0x1D400, 0x1D7FF, "Mathematical Alphanumeric Symbols"),
]


def report_coverage(entries):
    print("mapping coverage (mapped codepoints / block size)")
    print("  a codepoint the active font carries is rendered as-is, so this shares")
    print("  the work with the font; the chain only walks where the font is lacking.")
    print()
    for lo, hi, name in COVERAGE_BLOCKS:
        n = sum(1 for cp in range(lo, hi + 1) if cp in entries)
        total = hi - lo + 1
        print("  %-33s %5d / %-6d %5.1f%%" % (name, n, total, 100.0 * n / total))
    bmp = sum(1 for cp in range(0x0080, 0x10000) if cp in entries)
    print()
    print("  %-33s %5d / %-6d %5.1f%%" % ("whole BMP (above ASCII)", bmp,
                                          0x10000 - 0x80,
                                          100.0 * bmp / (0x10000 - 0x80)))
    print()
    print("  Decorative symbols have no decomposition, so U+263A and U+2713 stay")
    print("  unmapped by construction and resolve to the substitute.")


def block_name(cp):
    def between(lo, hi):
        return lo <= cp <= hi

    if cp < 0x0100:
        return "Latin-1 Supplement"
    if cp < 0x0180:
        return "Latin Extended-A"
    if cp < 0x0250:
        return "Latin Extended-B"
    if cp < 0x02B0:
        return "IPA Extensions"
    if cp < 0x0300:
        return "Spacing Modifier Letters"
    if cp < 0x0370:
        return "Combining Diacritical Marks"
    if cp < 0x0400:
        return "Greek and Coptic"
    if cp < 0x0500:
        return "Cyrillic"
    if cp < 0x0530:
        return "Cyrillic Supplement"
    if between(0x1E00, 0x1EFF):
        return "Latin Extended Additional"
    if between(0x1F00, 0x1FFF):
        return "Greek Extended"
    if cp < 0x2070:
        return "General Punctuation"
    if cp < 0x20A0:
        return "Super and Subscripts"
    if cp < 0x2100:
        return "Currency Symbols"
    if cp < 0x2150:
        return "Letterlike Symbols"
    if cp < 0x2190:
        return "Number Forms"
    if cp < 0x2200:
        return "Arrows"
    if cp < 0x2300:
        return "Mathematical Operators"
    if cp < 0x2500:
        return "Enclosed Alphanumerics"
    if cp < 0x2580:
        return "Box Drawing"
    if cp < 0x2600:
        return "Geometric Shapes"
    if cp < 0x2700:
        return "Miscellaneous Symbols"
    if cp < 0x2800:
        return "Dingbats"
    if cp < 0x2C60:
        return "Miscellaneous Symbols and Arrows"
    if cp < 0x2C80:
        return "Latin Extended-C"
    if cp < 0x3040:
        return "CJK Symbols and Punctuation"
    if cp < 0x3100:
        return "Kana"
    if cp < 0x3400:
        return "CJK Compatibility"
    if cp < 0xA000:
        return "CJK Unified Ideographs"
    if cp < 0xA6A0:
        return "Cyrillic Extended-B"
    if cp < 0xA800:
        return "Latin Extended-D"
    if cp < 0xD7B0:
        return "Hangul Syllables"
    if cp < 0x1D400:
        return "Presentation Forms"
    if cp < 0x1D800:
        return "Mathematical Alphanumeric Symbols"
    return "Other"


def main():
    entries = build()
    OUT_PATH.write_text(emit(entries), encoding="utf-8", newline="\n")

    print("wrote %s" % OUT_PATH.name)
    print("table entries : %d (%d bytes)" % (len(entries), len(entries) * 4))
    if "--stats" in sys.argv:
        print()
        report_coverage(entries)
    return 0


if __name__ == "__main__":
    sys.exit(main())
